version: '3.1'

services:
  properties-db:
    image: postgres:15.1
    container_name: properties-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data #host:container
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  properties-db-ui:
    image: michalhosna/adminer #adminer:4.8.1 #official image
    #https://github.com/michalhosna/adminer-docker
    container_name: properties-db-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DRIVER=pgsql
      - ADMINER_SERVER=properties-db
      - ADMINER_USERNAME=${POSTGRES_USER}
      - ADMINER_DB=${POSTGRES_DB}
      - ADMINER_PASSWORD=${POSTGRES_PASSWORD}
      - ADMINER_AUTOLOGIN=1
      - ADMINER_NAME=Idealista Project!

volumes:
  pgdata:
#networks:
#  idealista-net:
