version: '3.7'

services:

  predictor-api:
    container_name: predictor-api
    image: predi-api:latest
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # depends_on:
    #   -
    #volumes:
    #  - api-logs:/logs/predictor-api
    #environment:
    #  - API_PORT=
    restart: always
    #networks:
    #  - idealista-net

#networks:
#  idealista-net:
#    external: true

volumes:
  api-logs:
